package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import org.opencv.video.TrackerDaSiamRPN_Params;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.estimator.SwerveDrivePoseEstimator;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rectangle2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.LimelightHelpers;
import frc.robot.Constants.FieldConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
    public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    boolean useMegaTag2 = true; //set to false to use MegaTag1
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    private boolean blue = false;
    Optional<DriverStation.Alliance> alliance = DriverStation.getAlliance();
    Field2d m_field;
    private final SwerveDrivePoseEstimator m_poseEstimator;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    
    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
        m_field = new Field2d();
        m_poseEstimator = new SwerveDrivePoseEstimator(getKinematics(), getState().Pose.getRotation(), getState().ModulePositions, new Pose2d());
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
         m_poseEstimator = new SwerveDrivePoseEstimator(getKinematics(), getState().Pose.getRotation(), getState().ModulePositions, new Pose2d());
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
         m_poseEstimator = new SwerveDrivePoseEstimator(getKinematics(), getState().Pose.getRotation(), getState().ModulePositions, new Pose2d());
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    public boolean isBlue(){
        return blue;
    }

    @Override
    public void periodic() {
        SmartDashboard.putNumber("front left current",getModule(0).getDriveMotor().getStatorCurrent().getValueAsDouble());
         SmartDashboard.putNumber("front right current",getModule(1).getDriveMotor().getStatorCurrent().getValueAsDouble());
          SmartDashboard.putNumber("back right current",getModule(2).getDriveMotor().getStatorCurrent().getValueAsDouble());
           SmartDashboard.putNumber("back left current",getModule(3).getDriveMotor().getStatorCurrent().getValueAsDouble());
           SmartDashboard.putNumber("Hub Distance", getHubDistance());
        SmartDashboard.putNumber("Swerve Rotation", getState().Pose.getRotation().getDegrees());
        SmartDashboard.putNumber("Converted Swerve Rotation", convertSwerveRotation());
        blue = alliance.isPresent() ? alliance.get() == DriverStation.Alliance.Blue : false;
        System.out.println(blue);

//System.out.println(getState().Pose.getRotation().getDegrees());
        // if(DriverStation.isDisabled()){
        //     useMegaTag2 = false;
        // }
        // else{
        //     useMegaTag2 = true;
        // }

        SmartDashboard.putNumber("Steer Setpoint", 0);
        updateOdometry();
        m_field.setRobotPose(getState().Pose);
         SmartDashboard.putData("FieldWithVision", m_field);
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    public double convertSwerveRotation(){
        double robotRotation = getState().Pose.getRotation().getDegrees();
        if(robotRotation < 0){
            robotRotation += 360;
        }
        return robotRotation;
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public void updateOdometry(){
        LimelightHelpers.SetRobotOrientation("limelight-three", getState().Pose.getRotation().getDegrees(), 0, 0, 0, 0, 0);
        LimelightHelpers.SetRobotOrientation("limelight-four", getState().Pose.getRotation().getDegrees(), 0, 0, 0, 0, 0);
 m_poseEstimator.update(
        getState().Pose.getRotation(),
        getState().ModulePositions);

        boolean doRejectUpdateLL3G = false;
        boolean doRejectUpdateLL4 = false;

       
        boolean doRejectUpdate = false;

    if(useMegaTag2 == false)
    {
      LimelightHelpers.PoseEstimate mt1LL3G = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-threeG");
      LimelightHelpers.PoseEstimate mt1LL4 = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-four");
     
      if(mt1LL3G != null) {
      if(mt1LL3G.tagCount == 1 && mt1LL3G.rawFiducials.length == 1)
      {
        if(mt1LL3G.rawFiducials[0].ambiguity > .7)
        {
          doRejectUpdate = true;
        }
        if(mt1LL3G.rawFiducials[0].distToCamera > 3)
        {
          doRejectUpdate = true;
        }
      }
      if(mt1LL3G.tagCount == 0)
      {
        doRejectUpdate = true;
      }

      if(!doRejectUpdate)
      {
        super.setStateStdDevs(VecBuilder.fill(.7,.7,0.7));
        super.addVisionMeasurement(mt1LL3G.pose, mt1LL3G.timestampSeconds);
      }
    }
      if(mt1LL4 != null){
      if(mt1LL4.tagCount == 1 && mt1LL4.rawFiducials.length == 1)
      {
        if(mt1LL4.rawFiducials[0].ambiguity > .7)
        {
          doRejectUpdate = true;
        }
        if(mt1LL4.rawFiducials[0].distToCamera > 3)
        {
          doRejectUpdate = true;
        }
      }
      if(mt1LL4.tagCount == 0)
      {
        doRejectUpdate = true;
      }

      if(!doRejectUpdate)
      {
        super.setStateStdDevs(VecBuilder.fill(.7,.7,0.7));
        super.addVisionMeasurement(mt1LL4.pose, mt1LL4.timestampSeconds);
      }
    }
    }

    if (useMegaTag2 == true) {
        LimelightHelpers.PoseEstimate mt2LL3G = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-three");
        LimelightHelpers.PoseEstimate mt2LL4 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-four");
       if(mt2LL4 == null){System.out.println("LL4 is null" );}
    if(Math.abs(getState().Speeds.omegaRadiansPerSecond) > 360){
        doRejectUpdateLL3G = true;
        doRejectUpdateLL4 = true;
    }
    if(mt2LL3G != null){
    if(mt2LL3G.tagCount == 0||mt2LL3G.avgTagDist > 2.5){//3.5
        doRejectUpdateLL3G = true;
    }
   
    if(!doRejectUpdateLL3G){
        setStateStdDevs(VecBuilder.fill(.7,.7,99999999));
        addVisionMeasurement(mt2LL3G.pose, mt2LL3G.timestampSeconds);
    }
}
    if(mt2LL4 != null){
     if(mt2LL4.tagCount == 0 || mt2LL4.avgTagDist > 2.5){//3.5
        doRejectUpdateLL4 = true;
    }
    if(!doRejectUpdateLL4){
       // m_poseEstimator.setVisionMeasurementStdDevs(VecBuilder.fill(0.5,0.5,9999));
        //m_poseEstimator.addVisionMeasurement(mt2LL4.pose, mt2LL4.timestampSeconds);
        setVisionMeasurementStdDevs(VecBuilder.fill(0.7,0.7,99999999));
        addVisionMeasurement(mt2LL4.pose, mt2LL4.timestampSeconds);
        System.out.println("adding vision measurement!");
    }
}
    }
}
public Pose2d getVisionPose(){
    return m_poseEstimator.getEstimatedPosition();
}

public double getHubDistance(){
     Pose2d robotPose = getState().Pose;
     Translation2d goalPosition = blue?FieldConstants.blueHub:FieldConstants.redHub;
     return robotPose.getTranslation().getDistance(goalPosition);
}

public Translation2d getGoalPose(){

    Rectangle2d allianceZone = blue ? FieldConstants.blueAllianceZone : FieldConstants.redAllianceZone;
    Rectangle2d leftZone = blue ? FieldConstants.blueLeftZone : FieldConstants.redLeftZone;
    Rectangle2d rightZone = blue ? FieldConstants.blueRightZone : FieldConstants.redRightZone;
    Translation2d allianceZoneGoal = blue ? FieldConstants.blueHub : FieldConstants.redHub;
    Translation2d leftZoneGoal = blue ? FieldConstants.blueLeftZoneGoal : FieldConstants.redLeftZoneGoal;
    Translation2d rightZoneGoal = blue ? FieldConstants.blueRightZoneGoal : FieldConstants.redRightZoneGoal;

    Translation2d robotPose = getState().Pose.getTranslation();

    if(allianceZone.contains(robotPose)){
        return allianceZoneGoal;
    }
    else if(leftZone.contains(robotPose)){
        return leftZoneGoal;
    }
    else if(rightZone.contains(robotPose)){
        return rightZoneGoal;
    }
    else{
        return allianceZoneGoal;
    }
}

public double driveToClimbLeftX(){
    Translation2d distanceToClimb = getState().Pose.getTranslation().minus(blue ? FieldConstants.blueClimbLeft : FieldConstants.redClimbLeft);
    double xSpeed = 1 * distanceToClimb.getX();
    return xSpeed;
}
public double driveToClimbLeftY(){
 Translation2d distanceToClimb = getState().Pose.getTranslation().minus(blue ? FieldConstants.blueClimbLeft : FieldConstants.redClimbLeft);
    double ySpeed = 1 * distanceToClimb.getY();
    return ySpeed;
}
public double driveToClimbRightX(){
 Translation2d distanceToClimb = getState().Pose.getTranslation().minus(blue ? FieldConstants.blueClimbRight : FieldConstants.redClimbRight);
    double xSpeed = 1 * distanceToClimb.getX();
    return xSpeed;
}
public double driveToClimbRightY(){
 Translation2d distanceToClimb = getState().Pose.getTranslation().minus(blue ? FieldConstants.blueClimbRight : FieldConstants.redClimbRight);
    double ySpeed = 1 * distanceToClimb.getY();
    return ySpeed;
}
}